name: Build Flash Attention ROCm Windows (Distributed)

on:
  workflow_dispatch:

env:
  PYTORCH_ROCM_ARCH: "gfx1100;gfx1101;gfx1102;gfx1150;gfx1151;gfx1200;gfx1201"
  GPU_ARCHS: "gfx1100;gfx1101;gfx1102;gfx1150;gfx1151;gfx1200;gfx1201"
  FLASH_ATTN_LOCAL_VERSION: "rocm7.13torch2.11.0"
  CC: "clang-cl"
  CXX: "clang-cl"
  DISTUTILS_USE_SDK: "1"
  TORCH_ROCM_AOTRITON_ENABLE_EXPERIMENTAL: "FALSE"
  FLASH_ATTENTION_TRITON_AMD_ENABLE: "FALSE"

jobs:
  # --- 0. prepare dependencies ---
  prepare-deps:
    runs-on: windows-2022
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ./rocm_deps
          key: rocm-windows-deps-${{ env.FLASH_ATTN_LOCAL_VERSION }}-py3.10

      - name: Download dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install  numpy==1.26.4 setuptools==69.5.1 networkx==3.4.2
          python -m pip download torch==2.11.0+rocm7.13.0 torchvision==0.26.0+rocm7.13.0 torchaudio==2.11.0+rocm7.13.0 rocm[devel] --index-url https://repo.amd.com/rocm/whl/gfx120X-all --dest ./rocm_deps

  # --- 1-A. jobs divide part1 ---
  compile-chunk-part1:
    needs: prepare-deps
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        chunk: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

    steps:
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      - name: Checkout Flash Attention
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activate MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install PyTorch and ROCm SDK
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install  numpy==1.26.4 setuptools==69.5.1 networkx==3.4.2
          python -m pip install torch==2.11.0+rocm7.13.0 torchvision==0.26.0+rocm7.13.0 torchaudio==2.11.0+rocm7.13.0 rocm[devel] --index-url https://repo.amd.com/rocm/whl/gfx120X-all
          rocm-sdk init

      - name: Setup ROCm Dynamic Paths
        run: |
          $ROCM_ROOT = (rocm-sdk path --root).Trim()
          $ROCM_BIN = (rocm-sdk path --bin).Trim()
          echo "ROCM_HOME=$ROCM_ROOT" >> $env:GITHUB_ENV
          echo "$ROCM_ROOT\lib\llvm\bin" >> $env:GITHUB_PATH
          echo "$ROCM_BIN" >> $env:GITHUB_PATH
          echo "MAX_JOBS=$env:NUMBER_OF_PROCESSORS" >> $env:GITHUB_ENV

      - name: Compile Chunk ${{ matrix.chunk }} (Part 1)
        env:
          BUILD_CHUNK_INDEX: ${{ matrix.chunk }}
          BUILD_NUM_CHUNKS: 40
          BUILD_COMPILE_ONLY: "1" # skip link
        run: |
          # compile only
          python setup.py build_ext

      - name: Upload Chunk Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-objects-chunk-${{ matrix.chunk }}
          path: build/
          retention-days: 1


  # --- 1-B. jobs divide part2 ---
  compile-chunk-part2:
    needs: compile-chunk-part1  # wait part1
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        chunk: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]

    steps:
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      - name: Checkout Flash Attention
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activate MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Restore ROCm Dependencies
        uses: actions/cache/restore@v4
        with:
          path: ./rocm_deps
          key: rocm-windows-deps-${{ env.FLASH_ATTN_LOCAL_VERSION }}-py3.10

      - name: Install PyTorch and ROCm SDK
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install  numpy==1.26.4 setuptools==69.5.1 networkx==3.4.2
          python -m pip install torch==2.11.0+rocm7.13.0 torchvision==0.26.0+rocm7.13.0 torchaudio==2.11.0+rocm7.13.0 rocm[devel] --index-url https://repo.amd.com/rocm/whl/gfx120X-all
          rocm-sdk init

      - name: Setup ROCm Dynamic Paths
        run: |
          $ROCM_ROOT = (rocm-sdk path --root).Trim()
          $ROCM_BIN = (rocm-sdk path --bin).Trim()
          echo "ROCM_HOME=$ROCM_ROOT" >> $env:GITHUB_ENV
          echo "$ROCM_ROOT\lib\llvm\bin" >> $env:GITHUB_PATH
          echo "$ROCM_BIN" >> $env:GITHUB_PATH
          echo "MAX_JOBS=$env:NUMBER_OF_PROCESSORS" >> $env:GITHUB_ENV

      - name: Compile Chunk ${{ matrix.chunk }} (Part 1)
        env:
          BUILD_CHUNK_INDEX: ${{ matrix.chunk }}
          BUILD_NUM_CHUNKS: 40
          BUILD_COMPILE_ONLY: "1" # skip link
        run: |
          # compile only
          python setup.py build_ext

      - name: Upload Chunk Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-objects-chunk-${{ matrix.chunk }}
          path: build/
          retention-days: 1

  # --- 2. link and wheel ---
  link-wheel:
    needs: compile-chunk-part2
    runs-on: windows-2022
    strategy:
      matrix:
        python-version: ["3.10"]
        
    steps:
      - name: Enable long paths in Git
        run: git config --system core.longpaths true

      - name: Checkout Flash Attention
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Activate MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Format Python Version for PyTorch URL
        run: |
          $py_ver = "${{ matrix.python-version }}"
          $cp_ver = "cp" + $py_ver.Replace(".", "")
          echo "CP_VER=$cp_ver" >> $env:GITHUB_ENV

      - name: Restore ROCm Dependencies
        uses: actions/cache/restore@v4
        with:
          path: ./rocm_deps
          key: rocm-windows-deps-${{ env.FLASH_ATTN_LOCAL_VERSION }}-py3.10

      - name: Install PyTorch and ROCm SDK
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install  numpy==1.26.4 setuptools==69.5.1 networkx==3.4.2
          python -m pip install torch==2.11.0+rocm7.13.0 torchvision==0.26.0+rocm7.13.0 torchaudio==2.11.0+rocm7.13.0 rocm[devel] --index-url https://repo.amd.com/rocm/whl/gfx120X-all
          rocm-sdk init

      - name: Setup ROCm Dynamic Paths
        run: |
          $ROCM_ROOT = (rocm-sdk path --root).Trim()
          $ROCM_BIN = (rocm-sdk path --bin).Trim()
          echo "ROCM_HOME=$ROCM_ROOT" >> $env:GITHUB_ENV
          echo "$ROCM_ROOT\lib\llvm\bin" >> $env:GITHUB_PATH
          echo "$ROCM_BIN" >> $env:GITHUB_PATH
          echo "MAX_JOBS=$env:NUMBER_OF_PROCESSORS" >> $env:GITHUB_ENV

      - name: Download artifacts sequentially and merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          $artifactsJson = gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=99
          $artifacts = $artifactsJson | ConvertFrom-Json
          
          New-Item -ItemType Directory -Force -Path build/
          
          foreach ($artifact in $artifacts.artifacts) {
              if ($artifact.name -match "^compiled-objects-chunk-") {
                  Write-Host "Downloading $($artifact.name) ..."
                  $tempDir = "temp_$($artifact.name)"
                  
                  # download to tmp
                  gh run download ${{ github.run_id }} -n $artifact.name --dir $tempDir
                  
                  # tmp override build/ 
                  Copy-Item -Path "$tempDir\*" -Destination build\ -Recurse -Force
                  
                  # remove tmp
                  Remove-Item -Path $tempDir -Recurse -Force
              }
          }
        shell: pwsh

      - name: Generate Source Files
        run: |
          # dummy setup.py make CK code (generate.py)
          python setup.py --version

      - name: Link and Build Wheel
        env:
          BUILD_LINK_ONLY: "1"  # build link only
        run: |
          # skip Ninja
          python setup.py bdist_wheel

      - name: Upload Final Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flash-attn-${{ env.FLASH_ATTN_LOCAL_VERSION }}-${{ env.CP_VER }}-win_amd64
          path: dist/*.whl
